from enum import Enum

class enumTelas(Enum):
    TELA_LOGIN = 0
    TELA_MENU_USUARIO = 1
    TELA_AREAS_DISPONIVEIS = 2
    TELA_EVENTOS_AREA = 3
    TELA_EVENTOS_PROPRIOS = 4
    TELA_CRIAR_EVENTO = 5